In [20]:
from PIL import Image
import numpy as np 

im = Image.open('./data/test/test1.jpeg')
pixel = im.getdata()
a = np.array(pixel)
a=a.reshape(16,16)
print(a)

[[ 0 16  0  0 12  1  4  0  1  0  0  0  0  0  1  2]
 [ 0 17  0  3 10  0  7  0  1  1  2  3  4  5  6  6]
 [ 0 10  0  4  7  4 20  9  0  0  1  1  0  0  0  0]
 [ 6 24 21 31 30 38 64 48 32 32 32 30 24 17 10  6]
 [ 1 13 14 25 19 34 66 39 32 32 32 30 24 17 10  6]
 [ 0  0  0  3  0 10 42  1  0  0  1  1  0  0  0  0]
 [17 10  8 15  0 23 54  1  1  1  2  3  4  5  6  6]
 [12  1  0  7  0 21 52  0  1  0  0  0  0  0  1  2]
 [ 1 11  0  0  0 20 42  5  0  0  4  7  8  5  2  0]
 [ 0  9  0  1  1 18 38  1  5  5  5  5  4  3  2  1]
 [ 0  7  0  3  2 16 36  1  0  0  0  0  0  0  0  0]
 [ 0  6  0  2  1 15 40 12  1  1  1  2  3  5  7  9]
 [ 2  6  0  1  0 13 44 23  0  0  0  0  0  0  0  0]
 [ 3  6  0  2  0  8 39 23 44 45 47 47 43 36 29 25]
 [ 1  5  0  7  0  1 26  9 10 10 10  8  6  2  0  0]
 [ 0  5  1 12  1  0 14  0  1  0  0  0  0  1  3  5]]


In [8]:
## csv 제작

from PIL import Image
import numpy as np 
test_path ="./data/test/test"
#classifier = ['t','u','v','w','x','y','z']
pixel_list =[]

for i in range(1,21):
    path = test_path+f'{i}.jpeg'
    print(path)
    im = Image.open(path) 
    pixels = list(im.getdata())
    pixels.append((i-1)%7)
    pixel_list.append(pixels)
    
for i in range(21,141):
    path = test_path+f'{i}.jpg'
    print(path)
    im = Image.open(path) 
    pixels = list(im.getdata())
    pixels.append((i-1)%7)
    pixel_list.append(pixels)

#print(pixel_list)
myArray = np.empty((0,257))  # 0~255는 데이터 256은 라벨 
for pixel in pixel_list:
    myArray = np.append(myArray,np.array([pixel]),axis=0)
myArray = myArray.astype(np.float32)
np.savetxt("test.csv", myArray, delimiter=", ", newline="\n",fmt='%i')

./data/test/test1.jpeg
./data/test/test2.jpeg
./data/test/test3.jpeg
./data/test/test4.jpeg
./data/test/test5.jpeg
./data/test/test6.jpeg
./data/test/test7.jpeg
./data/test/test8.jpeg
./data/test/test9.jpeg
./data/test/test10.jpeg
./data/test/test11.jpeg
./data/test/test12.jpeg
./data/test/test13.jpeg
./data/test/test14.jpeg
./data/test/test15.jpeg
./data/test/test16.jpeg
./data/test/test17.jpeg
./data/test/test18.jpeg
./data/test/test19.jpeg
./data/test/test20.jpeg
./data/test/test21.jpg
./data/test/test22.jpg
./data/test/test23.jpg
./data/test/test24.jpg
./data/test/test25.jpg
./data/test/test26.jpg
./data/test/test27.jpg
./data/test/test28.jpg
./data/test/test29.jpg
./data/test/test30.jpg
./data/test/test31.jpg
./data/test/test32.jpg
./data/test/test33.jpg
./data/test/test34.jpg
./data/test/test35.jpg
./data/test/test36.jpg
./data/test/test37.jpg
./data/test/test38.jpg
./data/test/test39.jpg
./data/test/test40.jpg
./data/test/test41.jpg
./data/test/test42.jpg
./data/test/test43.jpg


In [9]:
train_path ="./data/train/train"
#classifier = ['t','u','v','w','x','y','z']
pixel_list =[]

for i in range(1,85):
    path = train_path+f'{i}.jpeg'
    print(path)
    im = Image.open(path) 
    pixels = list(im.getdata())
    pixels.append((i-1)%7)
    pixel_list.append(pixels)

for i in range(85,316):
    path = train_path+f'{i}.jpg'
    print(path)
    im = Image.open(path) 
    pixels = list(im.getdata())
    pixels.append((i-1)%7)
    pixel_list.append(pixels)

#print(pixel_list)
myArray = np.empty((0,257))  # 0~255는 데이터 256은 라벨 
for pixel in pixel_list:
    myArray = np.append(myArray,np.array([pixel]),axis=0)
myArray = myArray.astype(np.float32)
np.savetxt("train.csv", myArray, delimiter=", ", newline="\n",fmt='%i')

./data/train/train1.jpeg
./data/train/train2.jpeg
./data/train/train3.jpeg
./data/train/train4.jpeg
./data/train/train5.jpeg
./data/train/train6.jpeg
./data/train/train7.jpeg
./data/train/train8.jpeg
./data/train/train9.jpeg
./data/train/train10.jpeg
./data/train/train11.jpeg
./data/train/train12.jpeg
./data/train/train13.jpeg
./data/train/train14.jpeg
./data/train/train15.jpeg
./data/train/train16.jpeg
./data/train/train17.jpeg
./data/train/train18.jpeg
./data/train/train19.jpeg
./data/train/train20.jpeg
./data/train/train21.jpeg
./data/train/train22.jpeg
./data/train/train23.jpeg
./data/train/train24.jpeg
./data/train/train25.jpeg
./data/train/train26.jpeg
./data/train/train27.jpeg
./data/train/train28.jpeg
./data/train/train29.jpeg
./data/train/train30.jpeg
./data/train/train31.jpeg
./data/train/train32.jpeg
./data/train/train33.jpeg
./data/train/train34.jpeg
./data/train/train35.jpeg
./data/train/train36.jpeg
./data/train/train37.jpeg
./data/train/train38.jpeg
./data/train/train39.